version: '3.8'

services:
  api_dev:
    image: dockerlersnar/api-ts
    ports:
      - "5000:3000"
    depends_on:
      - link-db
    links:
      - link-db
  
  link-db:
    image: mongo:4.4
    ports:
      - "27017:27017"      
   